/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Document {
  'documentType' : DocumentType,
  'fileName' : string,
  'fileSize' : bigint,
  'employeeId' : string,
  'blobId' : ExternalBlob,
  'uploadedAt' : Time,
}
export interface DocumentStats {
  'totalEmployees' : bigint,
  'completionRate' : number,
  'totalDocuments' : bigint,
}
export type DocumentType = { 'passportPhoto' : null } |
  { 'class10Marksheet' : null } |
  { 'bankStatement' : null } |
  { 'experienceCertificate' : null } |
  { 'panCard' : null } |
  { 'mastersDegree' : null } |
  { 'aadharCard' : null } |
  { 'class12Marksheet' : null } |
  { 'bachelorsDegree' : null } |
  { 'diplomaCertificate' : null };
export interface Employee {
  'joinDate' : Time,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'employeeId' : string,
  'phone' : string,
  'department' : string,
}
export type ExternalBlob = Uint8Array;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDocument' : ActorMethod<
    [string, DocumentType, ExternalBlob, string, bigint],
    Document
  >,
  'addEmployee' : ActorMethod<[string, string, string, string, Time], Employee>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteDocument' : ActorMethod<[string, DocumentType], undefined>,
  'deleteEmployee' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDocumentStats' : ActorMethod<[], DocumentStats>,
  'getDocuments' : ActorMethod<[string], Array<Document>>,
  'getEmployee' : ActorMethod<[string], [] | [Employee]>,
  'getEmployees' : ActorMethod<[], Array<Employee>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateEmployee' : ActorMethod<[string, Employee], Employee>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];