/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const DocumentType = IDL.Variant({
  'passportPhoto' : IDL.Null,
  'class10Marksheet' : IDL.Null,
  'bankStatement' : IDL.Null,
  'experienceCertificate' : IDL.Null,
  'panCard' : IDL.Null,
  'mastersDegree' : IDL.Null,
  'aadharCard' : IDL.Null,
  'class12Marksheet' : IDL.Null,
  'bachelorsDegree' : IDL.Null,
  'diplomaCertificate' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const Document = IDL.Record({
  'documentType' : DocumentType,
  'fileName' : IDL.Text,
  'fileSize' : IDL.Nat,
  'employeeId' : IDL.Text,
  'blobId' : ExternalBlob,
  'uploadedAt' : Time,
});
export const Employee = IDL.Record({
  'joinDate' : Time,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'employeeId' : IDL.Text,
  'phone' : IDL.Text,
  'department' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DocumentStats = IDL.Record({
  'totalEmployees' : IDL.Nat,
  'completionRate' : IDL.Float64,
  'totalDocuments' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDocument' : IDL.Func(
      [IDL.Text, DocumentType, ExternalBlob, IDL.Text, IDL.Nat],
      [Document],
      [],
    ),
  'addEmployee' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time],
      [Employee],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteDocument' : IDL.Func([IDL.Text, DocumentType], [], []),
  'deleteEmployee' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDocumentStats' : IDL.Func([], [DocumentStats], ['query']),
  'getDocuments' : IDL.Func([IDL.Text], [IDL.Vec(Document)], ['query']),
  'getEmployee' : IDL.Func([IDL.Text], [IDL.Opt(Employee)], ['query']),
  'getEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateEmployee' : IDL.Func([IDL.Text, Employee], [Employee], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const DocumentType = IDL.Variant({
    'passportPhoto' : IDL.Null,
    'class10Marksheet' : IDL.Null,
    'bankStatement' : IDL.Null,
    'experienceCertificate' : IDL.Null,
    'panCard' : IDL.Null,
    'mastersDegree' : IDL.Null,
    'aadharCard' : IDL.Null,
    'class12Marksheet' : IDL.Null,
    'bachelorsDegree' : IDL.Null,
    'diplomaCertificate' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const Document = IDL.Record({
    'documentType' : DocumentType,
    'fileName' : IDL.Text,
    'fileSize' : IDL.Nat,
    'employeeId' : IDL.Text,
    'blobId' : ExternalBlob,
    'uploadedAt' : Time,
  });
  const Employee = IDL.Record({
    'joinDate' : Time,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'employeeId' : IDL.Text,
    'phone' : IDL.Text,
    'department' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DocumentStats = IDL.Record({
    'totalEmployees' : IDL.Nat,
    'completionRate' : IDL.Float64,
    'totalDocuments' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDocument' : IDL.Func(
        [IDL.Text, DocumentType, ExternalBlob, IDL.Text, IDL.Nat],
        [Document],
        [],
      ),
    'addEmployee' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time],
        [Employee],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteDocument' : IDL.Func([IDL.Text, DocumentType], [], []),
    'deleteEmployee' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDocumentStats' : IDL.Func([], [DocumentStats], ['query']),
    'getDocuments' : IDL.Func([IDL.Text], [IDL.Vec(Document)], ['query']),
    'getEmployee' : IDL.Func([IDL.Text], [IDL.Opt(Employee)], ['query']),
    'getEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateEmployee' : IDL.Func([IDL.Text, Employee], [Employee], []),
  });
};

export const init = ({ IDL }) => { return []; };